import crypto from "node:crypto";
import { eq } from "drizzle-orm";
import { db } from "../db/client";
import { ErrorCode, IMAGE_MIME, VIDEO_MIME, LIMITS } from "@newswatch/shared";
import { AppError } from "../errors/AppError";
import { presignPut, deleteObject } from "../config/r2";
import { mediaPipeline } from "../media/mediaPipeline";
import { mediaAssets } from "../db/schema";
import type { Principal } from "../middleware/auth";

/**
 * Mixed image/video upload lifecycle (REQ-REP-093..099, REQ-SYS-400..406).
 * Videos are transcoded + poster-generated by workers; only `ready` assets attach.
 */
export const mediaService = {
  async sign(input: {
    principal: Principal;
    kind: "image" | "video";
    contentType: string;
    sizeBytes: number;
    purpose: "avatar" | "article" | "hero" | "gallery" | "poster" | "video";
  }) {
    const { kind, contentType, sizeBytes } = input;

    if (kind === "image") {
      if (!IMAGE_MIME.includes(contentType as (typeof IMAGE_MIME)[number])) {
        throw new AppError(ErrorCode.UNSUPPORTED_MEDIA_TYPE, 415);
      }
      if (sizeBytes > LIMITS.imageMaxBytes) throw new AppError(ErrorCode.PAYLOAD_TOO_LARGE, 413);
    } else {
      if (!VIDEO_MIME.includes(contentType as (typeof VIDEO_MIME)[number])) {
        throw new AppError(ErrorCode.UNSUPPORTED_MEDIA_TYPE, 415);
      }
      if (sizeBytes > LIMITS.videoMaxBytes) throw new AppError(ErrorCode.VIDEO_TOO_LARGE, 413);
    }

    const ext = contentType.split("/")[1] ?? "bin";
    const key = `media/${kind}/${crypto.randomUUID()}.${ext}`;
    const [asset] = await db
      .insert(mediaAssets)
      .values({
        ownerId: input.principal.id,
        purpose: input.purpose,
        kind,
        status: "pending",
        processingStatus: "pending",
        storageKey: key,
        mimeType: contentType,
        sizeBytes,
      })
      .returning();
    const uploadUrl = await presignPut(key, contentType);
    return { assetId: asset!.id, key, uploadUrl, expiresInSec: 600, uploadType: "single" as const };
  },

  async complete(input: { principal: Principal; assetId: string; durationSeconds?: number }) {
    const [asset] = await db.select().from(mediaAssets).where(eq(mediaAssets.id, input.assetId)).limit(1);
    if (!asset) throw new AppError(ErrorCode.NOT_FOUND, 404);
    if (asset.ownerId !== input.principal.id && input.principal.role !== "super_admin") {
      throw new AppError(ErrorCode.FORBIDDEN, 403);
    }
    if (asset.kind === "video" && input.durationSeconds && input.durationSeconds > LIMITS.videoMaxSeconds) {
      await db
        .update(mediaAssets)
        .set({ processingStatus: "failed", processingError: "VIDEO_TOO_LONG" })
        .where(eq(mediaAssets.id, asset.id));
      throw new AppError(ErrorCode.VIDEO_TOO_LONG, 422);
    }
    // Enqueue the async pipeline: media.probe -> transcode -> poster.
    await mediaPipeline.enqueueProcessing(asset.id);
    const [updated] = await db.select().from(mediaAssets).where(eq(mediaAssets.id, asset.id)).limit(1);
    return { id: updated!.id, processingStatus: updated!.processingStatus, url: updated!.url };
  },

  async get(assetId: string) {
    const [asset] = await db.select().from(mediaAssets).where(eq(mediaAssets.id, assetId)).limit(1);
    if (!asset) throw new AppError(ErrorCode.NOT_FOUND, 404);
    return {
      id: asset.id,
      kind: asset.kind,
      processingStatus: asset.processingStatus,
      processingError: asset.processingError,
      url: asset.url,
      durationSeconds: asset.durationSeconds,
      width: asset.width,
      height: asset.height,
      variants: asset.variants,
    };
  },

  async remove(principal: Principal, assetId: string) {
    const [asset] = await db.select().from(mediaAssets).where(eq(mediaAssets.id, assetId)).limit(1);
    if (!asset) throw new AppError(ErrorCode.NOT_FOUND, 404);
    if (asset.ownerId !== principal.id && !["admin", "super_admin"].includes(principal.role)) {
      throw new AppError(ErrorCode.FORBIDDEN, 403);
    }
    await db.update(mediaAssets).set({ deletedAt: new Date() }).where(eq(mediaAssets.id, assetId));
    // TODO(P1b): enqueue `media_delete` worker.
    await deleteObject(asset.storageKey).catch(() => undefined);
    return { deleted: true };
  },

  async assertReady(assetId: string) {
    const [asset] = await db.select().from(mediaAssets).where(eq(mediaAssets.id, assetId)).limit(1);
    if (!asset || asset.deletedAt) throw new AppError(ErrorCode.NOT_FOUND, 404);
    if (asset.processingStatus !== "ready") {
      if (asset.processingStatus === "failed") throw new AppError(ErrorCode.MEDIA_PROCESSING_FAILED, 500);
      throw new AppError(ErrorCode.MEDIA_NOT_READY, 409);
    }
    return asset;
  },
};
