/**
 * Canonical error codes (docs/architecture/04-api.md §1.8).
 * Keep in sync with the API error handler.
 */
export const ErrorCode = {
  // 400
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_CURSOR: "INVALID_CURSOR",
  INVALID_SORT: "INVALID_SORT",
  INVALID_REFERENCE: "INVALID_REFERENCE",
  INVALID_TEMPLATE: "INVALID_TEMPLATE",
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",
  VIDEO_TOO_LARGE: "VIDEO_TOO_LARGE",
  VIDEO_TOO_LONG: "VIDEO_TOO_LONG",
  BAD_REQUEST: "BAD_REQUEST",

  // 401
  AUTH_REQUIRED: "AUTH_REQUIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_DELETED: "ACCOUNT_DELETED",
  OTP_INVALID: "OTP_INVALID",

  // 403
  FORBIDDEN: "FORBIDDEN",
  OUT_OF_SCOPE: "OUT_OF_SCOPE",
  REPORTER_NOT_APPROVED: "REPORTER_NOT_APPROVED",

  // 404
  NOT_FOUND: "NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  ARTICLE_NOT_FOUND: "ARTICLE_NOT_FOUND",
  TEMPLATE_NOT_FOUND: "TEMPLATE_NOT_FOUND",

  // 409
  CONFLICT: "CONFLICT",
  MEDIA_NOT_READY: "MEDIA_NOT_READY",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  REGION_HAS_CHILDREN: "REGION_HAS_CHILDREN",
  REGION_HAS_ARTICLES: "REGION_HAS_ARTICLES",

  // 413
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",

  // 422
  UNPROCESSABLE: "UNPROCESSABLE",

  // 423
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",

  // 429
  RATE_LIMITED: "RATE_LIMITED",
  OTP_RATE_LIMITED: "OTP_RATE_LIMITED",

  // 500/502
  INTERNAL_ERROR: "INTERNAL_ERROR",
  POSTER_RENDER_FAILED: "POSTER_RENDER_FAILED",
  MEDIA_PROCESSING_FAILED: "MEDIA_PROCESSING_FAILED",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const HttpStatusByErrorCode: Record<string, number> = {
  [ErrorCode.VALIDATION_ERROR]: 422,
  [ErrorCode.INVALID_CURSOR]: 400,
  [ErrorCode.INVALID_SORT]: 400,
  [ErrorCode.INVALID_REFERENCE]: 400,
  [ErrorCode.INVALID_TEMPLATE]: 422,
  [ErrorCode.UNSUPPORTED_MEDIA_TYPE]: 415,
  [ErrorCode.VIDEO_TOO_LARGE]: 413,
  [ErrorCode.VIDEO_TOO_LONG]: 422,
  [ErrorCode.BAD_REQUEST]: 400,
  [ErrorCode.AUTH_REQUIRED]: 401,
  [ErrorCode.TOKEN_INVALID]: 401,
  [ErrorCode.TOKEN_EXPIRED]: 401,
  [ErrorCode.INVALID_CREDENTIALS]: 401,
  [ErrorCode.ACCOUNT_DELETED]: 401,
  [ErrorCode.OTP_INVALID]: 400,
  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.OUT_OF_SCOPE]: 403,
  [ErrorCode.REPORTER_NOT_APPROVED]: 403,
  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.USER_NOT_FOUND]: 404,
  [ErrorCode.ARTICLE_NOT_FOUND]: 404,
  [ErrorCode.TEMPLATE_NOT_FOUND]: 404,
  [ErrorCode.CONFLICT]: 409,
  [ErrorCode.MEDIA_NOT_READY]: 409,
  [ErrorCode.INVALID_STATUS_TRANSITION]: 409,
  [ErrorCode.REGION_HAS_CHILDREN]: 409,
  [ErrorCode.REGION_HAS_ARTICLES]: 409,
  [ErrorCode.PAYLOAD_TOO_LARGE]: 413,
  [ErrorCode.UNPROCESSABLE]: 422,
  [ErrorCode.ACCOUNT_LOCKED]: 423,
  [ErrorCode.RATE_LIMITED]: 429,
  [ErrorCode.OTP_RATE_LIMITED]: 429,
  [ErrorCode.INTERNAL_ERROR]: 500,
  [ErrorCode.POSTER_RENDER_FAILED]: 502,
  [ErrorCode.MEDIA_PROCESSING_FAILED]: 500,
  [ErrorCode.SERVICE_UNAVAILABLE]: 503,
};
