const { withAppBuildGradle } = require("@expo/config-plugins");

/**
 * Silence the two noisy `hermesc` warning categories that React Native / Expo
 * runtime code always triggers:
 *
 *   - "the variable \"X\" was not declared"      -> -Wno-undefined-variable
 *   - "Direct call to eval()"                    -> -Wno-direct-eval
 *
 * These are false positives (Hermes does not know every host global such as
 * `fetch`, `Blob`, `setTimeout`, `nativeFabricUIManager`, ...), and the release
 * APK still builds. Adding the flags to `hermesFlags` keeps CI/build logs clean
 * without disabling all Hermes warnings.
 *
 * `android/` is gitignored and regenerated by `expo prebuild`, so this must live
 * in a config plugin rather than being edited into app/build.gradle by hand.
 */

const COMMENTED_FLAGS = '// hermesFlags = ["-O", "-output-source-map"]';
const TARGET_FLAGS =
  'hermesFlags = ["-O", "-output-source-map", "-Wno-undefined-variable", "-Wno-direct-eval"]';
const FALLBACK_ANCHOR = 'bundleCommand = "export:embed"';

module.exports = function withHermesSilentWarnings(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== "groovy") {
      throw new Error(
        "withHermesSilentWarnings: expected a Groovy app/build.gradle",
      );
    }

    let contents = cfg.modResults.contents;
    if (contents.includes(TARGET_FLAGS)) return cfg;

    if (contents.includes(COMMENTED_FLAGS)) {
      contents = contents.replace(COMMENTED_FLAGS, TARGET_FLAGS);
    } else if (contents.includes(FALLBACK_ANCHOR)) {
      contents = contents.replace(
        FALLBACK_ANCHOR,
        `${FALLBACK_ANCHOR}\n    ${TARGET_FLAGS}`,
      );
    } else {
      throw new Error(
        "withHermesSilentWarnings: could not locate the react { } block to set hermesFlags",
      );
    }

    cfg.modResults.contents = contents;
    return cfg;
  });
};
